# Generated by Django 5.0.7 on 2024-07-31 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopifyuser',
            old_name='shopify_id',
            new_name='customer_id',
        ),
    ]
