# Generated by Django 5.0.7 on 2024-08-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyuser',
            name='medicheck_patient_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shopifyuser',
            name='roseway_patient_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
