# Generated by Django 5.0.7 on 2024-08-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_shopifyuser_medicheck_patient_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyuser',
            name='choice_open',
            field=models.BooleanField(default=False),
        ),
    ]
