# Generated by Django 5.0.7 on 2024-08-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_shopifyuser_choice_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyuser',
            name='last_access_session',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
